name: Sync to Hugging Face
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true
      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          # Remplace 'ton_username' et 'nom_du_space' par tes infos HF
          git push --force https://ton_username:$HF_TOKEN@huggingface.co/spaces/ton_username/nom_du_space main